    create table bazaar.cart_item (
        current_price numeric(10,2) not null,
        quantity integer not null,
        bazaar_user_id bigint not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        primary key (id)
    );